CUDA:
  USE_CUDA: True
  CUDA_NUM: 4

DATASET:
  TYPE: "IdenticalFixed"
  ROOT: "/work/masatate/dataset/dataset_public"
  NUM_CLASSES: 19
  TRACK: [8, 3]
  CHECK_TRACK: 3

MODEL:
  TYPE: "audioToSeman"
  PRETRAINED: None

LOG:
  DIR: "./logs_identical_fixed"
  LOSS: 100
  IMAGE: 3000

RESULT:
  PATH: "./result_identical_fixed"
  SAVE_NUM: 3
  WEIGHT_PATH: "./checkpoint_identical_fixed"
  WEIGHT_ITER: 3000

TRAIN:
  LR: 0.00001
  BATCH_SIZE: 2
  NUM_WORKERS: 4
  EPOCH_START: 0
  EPOCH_END: 20
  VAL_EPOCH: 2
