CUDA: 
  USE_CUDA: 
  CUDA_NUM: 

DATASET: 
  TYPE: 
  ROOT: 
  NUM_CLASSES: 
  TRACK: 
  CHECK_TRACK: 
  ROTATE: 
  CROP: 

MODEL: 
  TYPE: 
  PRETRAINED: 

LOG: 
  DIR: 
  LOSS: 
  IMAGE: 

RESULT: 
  PATH: 
  SAVE_NUM: 
  WEIGHT_PATH: 
  WEIGHT_ITER: 

TRAIN: 
  LR: 
  BATCH_SIZE: 
  NUM_WORKERS: 
  EPOCH_START: 
  EPOCH_END: 
  VAL_EPOCH: 
