CUDA:
  USE_CUDA:
  CUDA_NUM:

DATASET:
  ROOT:
  NUM_CLASSES:
  TRACK:

MODEL:
  PRETRAINED:

LOG:
  DIR:
  LOSS:
  IMAGE:

RESULT:
  PATH:
  SAVE_NUM:
  WEIGHT_PATH:
  WEIGHT_ITER:

TRAIN:
  LR:
  BATCH_SIZE:
  NUM_WORKERS:
  EPOCH_START:
  EPOCH_END:
  VAL_EPOCH:
