CUDA:
  CUDA_NUM: 0
DATASET:
  TYPE: "SoundCityscapes"
  TRACK: [3, 8]

MODEL:
  TYPE: "audioToSeman"
  PRETRAINED: "./checkpoint_newloss_lr/checkpoint_epoch19.pth"

RESULT:
  PATH: "./result_newloss_lr"
  SAVE_NUM: 10