CUDA:
  CUDA_NUM: 8
DATASET:
  TYPE: "SoundCityscapesAuth"
  TRACK: [1, 6]

MODEL:
  TYPE: "audioToSeman"
  PRETRAINED: "./checkpoint_auth/checkpoint_epoch8.pth"

RESULT:
  PATH: "./result_auth"
  SAVE_NUM: 10